version: '3.8'

services:
  redis:
    container_name: events_adapter_redis
    image: redis/redis-stack:latest
    restart: always
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - ./data:/db